# Generated by Django 3.1.7 on 2021-09-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0009_orders_billing_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
